name: Deploy Production

on:
 push:
  branches:
   - main

jobs:
 deploy:
  runs-on: ubuntu-latest

  steps:
    - name: Checkout
      uses: actions/checkout@v5
  
    - name: Deploy to Production
      uses: Burnett01/rsync-deployments@7.0.0
      with:
        switches: >-
          -avzr
          --delete
          --exclude='.git'
          --exclude='.github'
          --exclude='.DS_Store'
          --exclude='README.md'
          --exclude='.gitignore'
          --exclude='test/'
        path: ./
        remote_path: /home/xb688956/n-material.info/public_html/
        remote_host: ${{ secrets.XSERVER_HOST }}
        remote_user: ${{ secrets.XSERVER_USER }}
        remote_key: ${{ secrets.XSERVER_KEY }}
        remote_port: 10022
        legacy_allow_rsa_hostkeys: true
